version: '3.8'

services:

#  app:
#    container_name: spring-boot-ldap
#    build:
#      dockerfile: Dockerfile
#    expose:
#      - "8080:8080"
#    depends_on:
#      - openldap
#    restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    driver: bridge
